### DISCUSSION TITLE
Feature Request: output as stream, not only speaker

### DISCUSSION THREAD

**Discussion by nagyrobi** [hassio-addons/addon-spotify-connect#201] [Ideas]
Please add support to play audio not only on local speakers, but on network audio players, like [ESPHome media player](https://esphome.io/components/media_player/index.html). 

How to do that: have an option just configure in this addon multiple output streams, which would show up on Spotify Connect as different speakers. Something like:
```
outputs:
- name: Local speakers
  type: local
- name: Living Room
  type: stream
  codec: mp3
  channels: stereo
  bitrate: 128
  mountpoint: livingroom.mp3
- name: Kitchen
  type: stream
  codec: mp3
  channels: stereo
  bitrate: 128
  mountpoint: kitchen.mp3
```
That could result in two mountpoint URLs like: 
```
http://homeassistant.local:8123/addon-spotify-connect/livingroom.mp3
http://homeassistant.local:8123/addon-spotify-connect/kitchen.mp3
````

We could configure two different ESPHome players based on 8266 or ESP32 playing these streams infinitely, and that's all.

We could use Icecast for stream service, eventually.
