### ISSUE TITLE
Does not show up in spotify.

### ISSUE THREAD

**Issue by parhedberg** [hassio-addons/addon-spotify-connect#27]
# Problem/Motivation

After some time, the connect instance is not shown in spotify. Before that no problem playing via the server.

## Expected behavior

To always show up in spotify, when started on hass.io

## Actual behavior

After some time (unclear how long) the server is not showing up in spotify. No info in the log. 
This might be a spotify issue, but restarting the server in hass.io fixes it every time..

## Steps to reproduce

Unclear.

## Proposed changes

Is there a heartbeat function, to keep the server alive?

**Comment by frenck** [comment]
In case of an actual crash of the service, it will restart by itself...

So there is something else going on, which is kinda not determinable using your report.

**Comment by daaaaa** [comment]
The very same thing happens to me.
This usually happen when my internet connetion stop to work.
When the connection comes back to work, hass.io is not visible anymore in spotify connect.

It appears i and only if I restart the add on.

**Comment by Cloudenius** [comment]
+1, same here. When I click "Refresh" to get the latest logs, no logs are showing. After restarting the add-on, it starts to work again.

**Comment by parhedberg** [comment]
I am sorry @frenck, but the logs are blank and the only symptom is that it is not shown in spotify. 

At one time i had something playing via this connect instance in spotify, and wanted to stop playing, but because spotify did not find it again, it could not be controlled. 

This could be a sign of that the hass.io server part is still running, but not showing up..

**Comment by davidake** [comment]
+1, I have the same problem.

**Comment by banditdk** [comment]
I have the same problem a lot.

Here is a log file where it dies playing a song.
And the hass.io player is not avalible in Spotify anymore.

https://pastebin.com/9EUQZjY7

**Comment by Cloudenius** [comment]
Created the following automation to get it restarted again. The name of the device is called "Receiver" on my Spotify client, so you might have to change that. Also check for the add-on name in the URL when opening the add-on within HassIO. I'm not sure if that name will change in the future.

I know it's not a solution, just an automated way to get the music going again. :)

```
- id: '15543859120495'
  alias: Restart Spotify Connect add-on
  trigger:
  - platform: template
    value_template: '{% if not "Receiver" in states.media_player.spotify.attributes.source_list %}True{% else %}False{% endif %}'
  condition: []
  action:
  - data:
      addon: a0d7b954_spotify
    service: hassio.addon_restart
```
